#ifndef DESKCLOCKCORE_GLOBAL_H
#define DESKCLOCKCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DESKCLOCKCORE_LIBRARY)
#  define DESKCLOCKCORE_EXPORT Q_DECL_EXPORT
#else
#  define DESKCLOCKCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // DESKCLOCKCORE_GLOBAL_H
